[phases.setup]
nixPkgs = ["python311"]

[phases.install]
cmds = ["pip install -r requirements.txt"]

[phases.build]
cmds = ["python -c 'print(\"Build complete\")'"]

[start]
cmd = "gunicorn complete_solar_app:app --host=0.0.0.0 --port=$PORT"
